### ISSUE TITLE
No such file or directory: 'conf/users.json' when load Docker container

### ISSUE THREAD

**Issue by Xangel2008** [SergeyPirogov/python-video-service#1]
Error log:

`$ docker run -p 8086 -v host_folder:/home/root/video video_service`
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import controllers
  File "/home/root/controllers.py", line 13, in <module>
    aaa = Cork('conf')
  File "/usr/local/lib/python2.7/dist-packages/cork/cork.py", line 95, in __init
__
    initialize=initialize
  File "/usr/local/lib/python2.7/dist-packages/cork/json_backend.py", line 68, i
n __init__
    self._refresh()  # load users and roles
  File "/usr/local/lib/python2.7/dist-packages/cork/json_backend.py", line 78, i
n _refresh
    self._loadjson(self._users_fname, self.users)
  File "/usr/local/lib/python2.7/dist-packages/cork/json_backend.py", line 101,
in _loadjson
    raise BackendIOException("Unable to read json file %s: %s" % (fname, e))
cork.base_backend.BackendIOException: Unable to read json file conf/users.json:
[Errno 2] No such file or directory: 'conf/users.json

```

**Comment by SergeyPirogov** [comment]
@Xangel2008 Is it happening when you run Docker container?

**Comment by SergeyPirogov** [comment]
fixed
